vens8:
	gcc SS.c -o SS
	gcc SC.c -o SC
	sleep 1
	xterm -geometry 150x32 -T "Server" -n "Server P1" -bg black -fg yellow -e bash -c './SS; exec bash' &
	sleep 1
	xterm -geometry 150x32 -T "Client 1" -n "Client 1" -bg black -fg yellow -e bash -c './SC; exec bash' &
	xterm -geometry 150x32 -T "Client 2" -n "Client 2" -bg black -fg yellow -e bash -c './SC; exec bash' &
	xterm -geometry 150x32 -T "Client 3" -n "Client 3" -bg black -fg yellow -e bash -c './SC; exec bash' &
	xterm -geometry 150x32 -T "Client 4" -n "Client 4" -bg black -fg yellow -e bash -c './SC; exec bash' &
	xterm -geometry 150x32 -T "Client 5" -n "Client 5" -bg black -fg yellow -e bash -c './SC; exec bash' &
	xterm -geometry 150x32 -T "Client 6" -n "Client 6" -bg black -fg yellow -e bash -c './SC; exec bash' &
	xterm -geometry 150x32 -T "Client 7" -n "Client 7" -bg black -fg yellow -e bash -c './SC; exec bash' &
	xterm -geometry 150x32 -T "Client 8" -n "Client 8" -bg black -fg yellow -e bash -c './SC; exec bash' &
	xterm -geometry 150x32 -T "Client 9" -n "Client 9" -bg black -fg yellow -e bash -c './SC; exec bash' &
	xterm -geometry 150x32 -T "Client 10" -n "Client 10" -bg black -fg yellow -e bash -c './SC; exec bash' &
